### ISSUE TITLE
hpe_project_ver default (16.02) problem in CentOS

### ISSUE THREAD

**Issue by pyguy** [pyguy/ansible-hpe-software#1]
It seems that HP has recently removed 10.62 from CentOS repository which is our default repo version, it's awkward! :confused: anyway I resolved it and changed the default to current on v1.2.3 tag, it can also be changed in the vars file or defined in your test yml file.
```yml
---
- hosts: localhost
  remote_user: root
  check_model: true
  hpe_project_ver: current

  roles:
      - pyguy.hpe_software
```

Thanks to @alikhajeh1
